### ISSUE TITLE
Map not loading under Firefox 50

### ISSUE THREAD

**Issue by PanierAvide** [plepe/ptmap#3]
Hello,
The page isn't loading under Firefox 50.0.2 (Arch Linux 64bits), due to a JS error:
```
TypeError: invalid 'in' operand ipLoc
```
The error comes from this part of the code:
```
if ('checkIPLocation' in config.location && config.location.checkIPLocation) {
    ipLocation('', function (err, ipLoc) {
      if ('latitude' in ipLoc) {
        map.setView([ ipLoc.latitude, ipLoc.longitude ], 14)
      } else {
        map.setView([ config.location.lat, config.location.lon ], config.location.zoom)
      }

      init2()
    })
  } else {
```
Regards.

**Comment by hfs** [comment]
This is a subsequent error from `_ipLocation()` where the request to freegeoip.net seems to fail. In case of errors above function gets called back with only `err` defined.

![ptmap_freegeoip](https://cloud.githubusercontent.com/assets/538109/22370493/f155da84-e491-11e6-85e1-0e51502fa705.png)

In my case the request to freegeoip.net was blocked by an ad-blocker. If I disable the ad-blocker the site works fine.

The code should be made more robust nevertheless.
