### ISSUE TITLE
No Stadtbahn in Stuttgart

### ISSUE THREAD

**Issue by PaulestOSM** [plepe/ptmap#4]
The map only shows buses and railway in Stuttgart, but no Stadtbahn. This map is thru this not really useful there.

**Comment by plepe** [comment]
Are you sure, that the Stadtbahn is entered to the OpenStreetMap? If yes, could you post an example. If you don't know what I'm talking about, can you describe where the Stadtbahn is running, so that I can check?

Here is information how to enter routes correctly to the OpenStreetMap: http://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport (nothing for newcomers, route mapping is rather complex).

**Comment by PaulestOSM** [comment]
Hello Stephan,

I cannot reach https://ptmap.plepe.at anymore. Is it possible that 193.196.137.152 is blocked?

Cheers,

Michael

Von: Stephan Bösch-Plepelits [mailto:notifications@github.com]
Gesendet: Dienstag, 31. Januar 2017 21:35
An: plepe/ptmap
Cc: Michael Paulmann; Author
Betreff: Re: [plepe/ptmap] No Stadtbahn in Stuttgart (#4)


Are you sure, that the Stadtbahn is entered to the OpenStreetMap? If yes, could you post an example. If you don't know what I'm talking about, can you describe where the Stadtbahn is running, so that I can check?

Here is information how to enter routes correctly to the OpenStreetMap: http://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport (nothing for newcomers, route mapping is rather complex).

**Comment by plepe** [comment]
No, hardware problems with the power supply at the VM host. Hope they get resolved soon (it's the second downtime during the last week).

**Comment by PaulestOSM** [comment]
Hello Stephan,

https://ptmap.plepe.at/#lat=48.79193&lon=9.20119&zoom=17

Here you can see a lightrail (Stadtbahn) track without line and stations from ptmap.

http://www.openstreetmap.org/way/207373289#map=17/48.79157/9.20128

Here you see the same object in openstreetmap, you see there is a lightrail (Stadtbahn).

Cheers,

Michael



Von: Stephan Bösch-Plepelits [mailto:notifications@github.com]
Gesendet: Dienstag, 31. Januar 2017 21:35
An: plepe/ptmap
Cc: Michael Paulmann; Author
Betreff: Re: [plepe/ptmap] No Stadtbahn in Stuttgart (#4)


Are you sure, that the Stadtbahn is entered to the OpenStreetMap? If yes, could you post an example. If you don't know what I'm talking about, can you describe where the Stadtbahn is running, so that I can check?

Here is information how to enter routes correctly to the OpenStreetMap: http://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport (nothing for newcomers, route mapping is rather complex).

**Comment by plepe** [comment]
As the hardware problems seem to take longer I temporarily moved to a different host - hope everything works after the DNS is updated.

I forgot to include `route=light_rail` in the configuration. Added (not commited yet).
